name: Build and Deploy

#add your main branch to build and run
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-web-app

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4

    - name: Install dependencies
      working-directory: my-web-app
      run: npm install

    - name: Build
      working-directory: my-web-app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./my-web-app/build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./my-web-app/build
